/* Native static application. Untrusted source content is rendered as text. */
(() => {
  'use strict';
  const data=JSON.parse(document.getElementById('research-data').textContent), M=ResearchMath;
  const records=data.instruments || [], bySymbol=new Map(records.map(r=>[r.symbol,r]));
  const content=document.getElementById('content'), colors=['#a8e5b1','#89bde0','#ddb9ed','#edbe86','#f2988f','#c2cf86'];
  const labels={entrydesk:'Entry desk',technical:'Desk Tape technicals',home:'Overview',screener:'Stock screener',compare:'Compare stocks',funds:'Funds & ETFs','fund-compare':'Compare funds',families:'Fund families',lists:'Research lists',portfolio:'Portfolio X-Ray',markets:'Today’s market',earnings:'Earnings calendar',dividends:'Dividend calendar',ipos:'IPO calendar',economy:'Economy',europe:'European markets',news:'Latest news',reads:'Longer reads',breakout:'Breakout screener',crypto:'Crypto markets',coverage:'Data coverage'};
  const metrics={market_cap:['Market cap','money',1e9,'billions, trading currency'],pe:['P/E','number',1,'trailing earnings; loss-making companies may be unavailable'],pb:['Price / book','number',1,'market price relative to book value'],revenue_growth:['Revenue growth','percent',.01,'provider year-over-year growth'],earnings_growth:['Earnings growth','percent',.01,'provider year-over-year growth'],operating_margin:['Operating margin','percent',.01,'operating profit / revenue'],net_margin:['Net margin','percent',.01,'net income / revenue'],roe:['Return on equity','percent',.01,'provider return on equity'],debt_equity:['Debt / equity','number',1,'decimal ratio'],dividend_yield:['Dividend yield','percent',.01,'provider trailing/indicated yield'],relative_volume:['Relative volume','number',1,'latest volume / preceding 20-session mean'],assets:['Fund assets','money',1e9,'billions, fund currency'],expense:['Expense ratio','percent',.01,'annual reported fund cost'],annualized:['Annualized return','percent',.01,'adjusted available history; minimum 1 year'],volatility:['Volatility','percent',.01,'annualized monthly returns; minimum 12 months'],drawdown:['Max drawdown','percent',.01,'available adjusted price history'],day:['Day','percent',.01,'latest adjusted close vs preceding session'],week:['Week','percent',.01,'last available observation at least 7 days earlier'],month:['Month','percent',.01,'last available observation at least 30 days earlier'],ytd:['This year','percent',.01,'from last observation before January 1'],year:['1 year','percent',.01,'last observation at least 365 days earlier'],revenue:['Revenue','money',1e9,'billions, reporting currency'],fcf_margin:['Free cash margin','percent',.01,'provider free cash flow / revenue'],current_ratio:['Current ratio','number',1,'current assets / current liabilities']};
  const storage={get(key,fallback){try{return JSON.parse(localStorage.getItem('mw:'+key))??fallback;}catch{return fallback;}},set(key,value){try{localStorage.setItem('mw:'+key,JSON.stringify(value));return true;}catch{return false;}}};
  function el(tag,attrs={},...children){const node=document.createElement(tag);for(const [key,value] of Object.entries(attrs)){if(key.startsWith('on'))node.addEventListener(key.slice(2),value);else if(key==='class')node.className=value;else if(value!=null)node.setAttribute(key,String(value));}for(const child of children.flat(Infinity))if(child!=null)node.append(child instanceof Node?child:document.createTextNode(String(child)));return node;}
  function button(text,fn,cls=''){return el('button',{type:'button',class:cls,onclick:fn},text);}
  function link(text,url,attrs={}){return el('a',{href:url,...attrs},text);}
  function external(text,url){try{const parsed=new URL(url);return ['http:','https:'].includes(parsed.protocol)?link(text,url,{target:'_blank',rel:'noopener noreferrer'}):el('span',{},text);}catch{return el('span',{},text);}}
  const num=(x,places=2)=>M.numeric(x)?new Intl.NumberFormat('en-US',{maximumFractionDigits:places}).format(x):'—';
  const percent=x=>M.numeric(x)?`${x>0?'+':''}${num(x*100)}%`:'—';
  const money=(x,currency='')=>M.numeric(x)?`${currency==='USD'?'$':currency==='EUR'?'€':currency?currency+' ':''}${Math.abs(x)>=1e12?num(x/1e12)+'T':Math.abs(x)>=1e9?num(x/1e9)+'B':Math.abs(x)>=1e6?num(x/1e6)+'M':num(x)}`:'—';
  const metric=(r,key)=>metrics[key]?.[1]==='percent'?percent(r.metrics?.[key]):metrics[key]?.[1]==='money'?money(r.metrics?.[key],['revenue','cash','debt','free_cash_flow'].includes(key)?r.financial_currency||r.currency:r.currency):num(r.metrics?.[key]);
  const tone=x=>M.numeric(x)?x>0?'up':x<0?'down':'muted':'muted';
  const stamp=value=>value?new Date(typeof value==='number'?value*1000:value).toLocaleString('en-GB',{timeZone:'Asia/Singapore',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})+' SGT':'Date unavailable';
  const note=text=>el('p',{class:'source-note'},text);
  const empty=text=>el('div',{class:'card empty'},text);
  function header(title,description,section='Research'){const node=el('div',{class:'page-header'},el('div',{},el('div',{class:'eyebrow'},section+' / Market Watch'),el('h1',{},title),el('p',{},description)),el('span',{class:'tag'},el('span',{class:'status-dot'}),data.mode==='live'?'FREE-SOURCE SNAPSHOT':'SYNTHETIC DEMO'));content.append(node);}
  function section(title,url,label='View all ↗'){return el('div',{class:'section-title'},el('h2',{},title),url?link(label,url):null);}
  function resourceNote(group=''){const resources=(data.resources||[]).filter(r=>!group||r.id.includes(group));const failed=resources.filter(r=>r.status!=='ok');return note(`${records.length} published instruments · Snapshot ${stamp(data.generated_at)}. ${failed.length?`${failed.length} ${group||'source'} resources stale or unavailable. `:''}Prices may be delayed or in-progress; this page does not refresh feeds. `);}
  function options(values,any){return [el('option',{value:''},any),...values.map(x=>el('option',{value:x},x))];}
  function table(columns,rows){return el('div',{class:'tablewrap'},el('table',{},el('thead',{},el('tr',{},columns.map(c=>el('th',{},c)))),el('tbody',{},rows.length?rows.map(row=>el('tr',{},row.map(cell=>el('td',{},cell)))):el('tr',{},el('td',{colspan:columns.length,class:'empty'},'No available records match this view.')))));}
  function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=link('',url,{download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function csv(rows,keys){const quote=x=>'"'+String(x??'').replaceAll('"','""')+'"';return [keys.map(quote).join(','),...rows.map(r=>keys.map(k=>quote(k in r?r[k]:r.metrics?.[k])).join(','))].join('\r\n');}
  function instrumentLink(r){return link(r.symbol,`#/instrument/${encodeURIComponent(r.symbol)}`);}
  function stockRows(rows,keys=['sector','price','market_cap','pe','revenue_growth','day']){return rows.map(r=>[el('div',{},instrumentLink(r),el('small',{},r.name)),...keys.map(k=>k==='price'?money(r.price,r.currency):k==='sector'?r.sector:el('span',{class:['day','week','month','year','ytd'].includes(k)?tone(r.metrics?.[k]):''},metric(r,k)))]);}
  function stockTable(rows,keys){const used=keys||['sector','price','market_cap','pe','revenue_growth','day'];return table(['Instrument',...used.map(k=>k==='price'?'Price':k==='sector'?'Sector':metrics[k]?.[0]||k)],stockRows(rows,used));}
  function chart(dates,series,label,unit='number'){
    if(dates.length<2||!series.length)return empty('Not enough aligned history to chart.');
    const valid=series.flatMap(s=>s.values).filter(M.numeric);if(!valid.length)return empty('History is unavailable.');
    const lo=Math.min(...valid),hi=Math.max(...valid),span=hi-lo||1,w=720,h=230;
    const wrap=el('div',{}),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('class','chart');svg.setAttribute('role','img');svg.setAttribute('aria-label',label);
    const svgEl=(name,attrs,text)=>{const n=document.createElementNS(svg.namespaceURI,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.append(n);return n;};
    const y=v=>190-(v-lo)/span*155;
    for(let i=0;i<4;i++){const value=lo+span*i/3;svgEl('line',{x1:50,x2:700,y1:y(value),y2:y(value),class:'axis'});svgEl('text',{x:0,y:y(value)+3},unit==='money'?money(value):num(value));}
    series.forEach((s,i)=>{let path='',gap=true;s.values.forEach((v,j)=>{if(M.numeric(v)){path+=`${gap?'M':'L'}${50+j/Math.max(dates.length-1,1)*650},${y(v)} `;gap=false;}else gap=true;});svgEl('path',{d:path,fill:'none',stroke:colors[i%colors.length],'stroke-width':2});});
    svgEl('text',{x:50,y:217},dates[0]);svgEl('text',{x:610,y:217},dates.at(-1));wrap.append(svg,el('div',{class:'legend'},series.map((s,i)=>el('span',{},el('i',{style:`background:${colors[i%colors.length]}`}),s.symbol))));
    const selected=dates.map((d,i)=>[d,...series.map(s=>num(s.values[i]))]);wrap.append(el('details',{class:'chart-table'},el('summary',{},'View chart data'),table(['Date',...series.map(s=>s.symbol)],selected)));return wrap;
  }
  function priceChart(r,limit=260){const rows=(r.history||[]).slice(-limit);return chart(rows.map(p=>p.date),[{symbol:r.symbol,values:rows.map(p=>p.close)}],r.symbol+' adjusted price history');}
  function miniInstrument(r,key='day'){return el('div',{class:'mini-row'},el('div',{},instrumentLink(r),el('small',{},r.name)),el('span',{class:tone(r.metrics?.[key])},percent(r.metrics?.[key])));}
  function indexCards(symbols){return el('div',{class:'grid four'},symbols.map(symbol=>{const r=bySymbol.get(symbol);return el('a',{class:'card',href:`#/instrument/${encodeURIComponent(symbol)}`},el('div',{class:'stat-label'},symbol),el('div',{class:'stat-value '+tone(r?.metrics?.day)},percent(r?.metrics?.day)),el('small',{},r?.name||'Not in this snapshot'),note(r?money(r.price,r.currency)+' · '+(r.as_of||'date unavailable'):'Price unavailable'));}));}
  function home(){header('A clearer view of the market.','Companies, funds, market moves and the stories behind them — in one research desk.','Overview');const spy=bySymbol.get('SPY');content.append(el('div',{class:'hero'},el('div',{},el('div',{class:'eyebrow'},'Research with perspective'),el('h1',{},'Find the facts.\nSee the bigger picture.'),el('p',{},'Screen companies, compare investments and look through your funds. Keep your breakout evidence one click away.'),el('div',{class:'actions'},link('Explore the screener ↗','#/screener',{class:'primary'}),link('See today’s market →','#/markets'))),el('div',{class:'hero-chart'},el('div',{class:'stat-label'},'S&P 500 · SPY / Adjusted history'),spy?priceChart(spy,90):empty('Run a research refresh to load market history.'))));content.append(section('The market at a glance','#/markets'),indexCards(['SPY','QQQ','TLT','GLD']));
    const stocks=records.filter(r=>r.kind==='stock'&&r.region==='US'&&M.numeric(r.metrics?.day));
    const sorted=[...stocks].sort((a,b)=>b.metrics.day-a.metrics.day);
    content.append(section('On the radar'),el('div',{class:'grid'},el('div',{class:'card'},el('h3',{},'Leading the day'),sorted.slice(0,5).map(r=>miniInstrument(r))),el('div',{class:'card'},el('h3',{},'Under pressure'),sorted.slice(-5).reverse().map(r=>miniInstrument(r))),el('div',{class:'card'},el('div',{class:'eyebrow'},'Your strategy'),el('h3',{},'Breakout & breakdown desk'),el('p',{},'Daily stocks. 4H crypto. Confirmed candle evidence, planned levels and your paper journal.'),link('Open breakout screener ↗','#/breakout'))));
    content.append(section('Worth knowing','#/news'),newsCards((data.news||[]).slice(0,3)),resourceNote());
  }
  function screener(kind){const fund=kind==='fund';header(fund?'Find your next fund.':'Companies that fit your criteria.',fund?'Compare costs, returns and reported holdings across the published fund universe.':'Filter financials and price performance. Missing values never pass an active numeric filter.');
    let state={query:'',region:'',sector:'',family:'',category:'',ranges:{},sort:fund?'assets':'market_cap',ascending:false};
    const params=new URLSearchParams(location.hash.split('?')[1]||'');if(params.has('screen'))try{state={...state,...M.validateScreen(JSON.parse(params.get('screen')),Object.keys(metrics))};}catch{}
    const query=el('input',{type:'search',placeholder:'Ticker or company',value:state.query}),region=el('select',{},options(['US','EU'],'All regions')),sector=el('select',{},options([...new Set(records.filter(r=>r.kind===kind).map(r=>r.sector))].sort(),'All sectors')),family=el('select',{},options([...new Set(records.filter(r=>r.kind===kind).map(r=>r.family))].sort(),'All families')),category=el('select',{},options([...new Set(records.filter(r=>r.kind===kind).map(r=>r.category))].sort(),'All categories'));
    region.value=state.region;sector.value=state.sector;family.value=state.family;category.value=state.category;
    const metricKeys=fund?['assets','expense','dividend_yield','annualized','volatility','drawdown','year','month']:['market_cap','pe','pb','revenue_growth','earnings_growth','operating_margin','net_margin','roe','debt_equity','dividend_yield','relative_volume','fcf_margin'];
    const count=el('p',{class:'source-note'}),body=el('div',{}),message=el('p',{class:'source-note','aria-live':'polite'}),saveName=el('input',{placeholder:'Screen name','aria-label':'Saved screen name'}),saved=el('select',{'aria-label':'Load saved screen'},options(Object.keys(storage.get('screens',{})),'Saved screens…'));
    const columnOptions=el('select',{'aria-label':'Additional table metric'},metricKeys.map(k=>el('option',{value:k},metrics[k][0])));columnOptions.value=fund?'expense':'pe';
    const rangeInputs={};const filterGrid=el('div',{class:'filter-grid'},metricKeys.map(key=>{const scale=metrics[key][2],range=state.ranges[key]||{},min=el('input',{type:'number',step:'any',placeholder:'Min',value:range.min==null?'':range.min/scale,'aria-label':metrics[key][0]+' minimum'}),max=el('input',{type:'number',step:'any',placeholder:'Max',value:range.max==null?'':range.max/scale,'aria-label':metrics[key][0]+' maximum'});rangeInputs[key]=[min,max];[min,max].forEach(input=>input.addEventListener('input',()=>{if(min.value===''&&max.value==='')delete state.ranges[key];else state.ranges[key]={min:min.value===''?null:Number(min.value)*scale,max:max.value===''?null:Number(max.value)*scale};draw();}));return el('label',{},metrics[key][0]+(metrics[key][1]==='percent'?' (%)':metrics[key][1]==='money'?' (B)':''),el('div',{class:'range'},min,max),el('div',{class:'metric-def'},records.filter(r=>r.kind===kind&&M.numeric(r.metrics?.[key])).length+' available'));}));
    function matching(){return M.filterInstruments(records,{...state,kind}).sort((a,b)=>{const av=a.metrics?.[state.sort],bv=b.metrics?.[state.sort];if(metrics[state.sort]?.[1]==='money'){const ac=state.sort==='revenue'?a.financial_currency||a.currency:a.currency,bc=state.sort==='revenue'?b.financial_currency||b.currency:b.currency;if(ac!==bc)return ac.localeCompare(bc);}if(!M.numeric(av))return M.numeric(bv)?1:0;if(!M.numeric(bv))return -1;return (state.ascending?1:-1)*(av-bv);});}
    function draw(){const rows=matching();count.textContent=`${rows.length} of ${records.filter(r=>r.kind===kind).length} ${fund?'funds':'companies'} match · Click a metric heading to sort · monetary ranks grouped by currency`;const keys=fund?['price','assets',columnOptions.value,'year','volatility','drawdown']:['sector','price','market_cap',columnOptions.value,'revenue_growth','day'];const t=stockTable(rows,keys);t.querySelectorAll('th').forEach((th,i)=>{const key=keys[i-1];if(metrics[key])th.replaceChildren(button(metrics[key][0]+(state.sort===key?(state.ascending?' ↑':' ↓'):''),()=>{state.ascending=state.sort===key?!state.ascending:false;state.sort=key;draw();}));});body.replaceChildren(t);}
    [query,region,sector,family,category].forEach((input,i)=>input.addEventListener('input',()=>{state[['query','region','sector','family','category'][i]]=input.value;draw();}));columnOptions.addEventListener('change',draw);
    saved.addEventListener('change',()=>{const screen=storage.get('screens',{})[saved.value];if(screen)location.hash=`#/${fund?'funds':'screener'}?screen=${encodeURIComponent(JSON.stringify(screen))}`;});
    const toolbar=el('div',{class:'toolbar'},el('label',{},'Search',query),el('label',{},'Region',region),el('label',{},fund?'Family':'Sector',fund?family:sector),fund?el('label',{},'Category',category):null,el('label',{},'Table metric',columnOptions),button('Reset',()=>{location.hash=`#/${fund?'funds':'screener'}`;render();}),button('Export CSV ↓',()=>download('market-watch-screen.csv',csv(matching(),['symbol','name','currency','price',...metricKeys]),'text/csv')));
    content.append(toolbar,el('details',{class:'card filter-panel',open:Object.keys(state.ranges).length?'':null},el('summary',{},'Financial & performance filters'),filterGrid),el('div',{class:'toolbar'},saveName,button('Save screen',()=>{const name=saveName.value.trim();if(!name)return;const screens=storage.get('screens',{});screens[name]=state;message.textContent=storage.set('screens',screens)?'Screen saved in this browser.':'Browser storage unavailable; use Share to preserve this screen.';saved.replaceChildren(...options(Object.keys(screens),'Saved screens…'));}),saved,button('Share screen ↗',()=>{const url=location.href.split('#')[0]+`#/${fund?'funds':'screener'}?screen=${encodeURIComponent(JSON.stringify(state))}`;message.replaceChildren(link('Open or copy this screen link',url));navigator.clipboard?.writeText(url).catch(()=>{});})),message,count,body,resourceNote('Yahoo'),el('details',{},el('summary',{},'Metric definitions and units'),table(['Metric','Definition'],metricKeys.map(k=>[metrics[k][0],metrics[k][3]]))));draw();
  }
  function detail(symbol){const r=bySymbol.get(symbol);if(!r){header('Instrument not loaded.','Search covers the published universe. Add this ticker to research.json and run a research refresh.');content.append(empty(symbol+' is not in this snapshot.'),link('Return to screener','#/screener'));return;}header(r.name,r.symbol+' · '+r.kind+' · '+r.region+' · '+r.country+' · '+r.sector);content.append(el('div',{class:'grid four'},el('div',{class:'card'},el('div',{class:'stat-label'},'Price / '+r.currency),el('div',{class:'stat-value'},money(r.price,r.currency)),note(r.as_of||'Observation date unavailable')),el('div',{class:'card'},el('div',{class:'stat-label'},'Day move'),el('div',{class:'stat-value '+tone(r.metrics?.day)},percent(r.metrics?.day)),note('Adjusted price change')),el('div',{class:'card'},el('div',{class:'stat-label'},r.kind==='fund'?'Annual expense':'Market cap'),el('div',{class:'stat-value'},metric(r,r.kind==='fund'?'expense':'market_cap')),note('Yahoo-normalized research')),el('div',{class:'card'},el('div',{class:'stat-label'},'1 year'),el('div',{class:'stat-value '+tone(r.metrics?.year)},percent(r.metrics?.year)),note('Available adjusted history'))),section('Price history'),el('div',{class:'card'},priceChart(r,1300)),note(r.source||'Source unavailable'),r.description?el('div',{class:'card'},el('h2',{},'About'),el('p',{},r.description)):null,section('Facts & financials'),table(['Metric','Value','Definition'],Object.keys(metrics).filter(k=>M.numeric(r.metrics?.[k])).map(k=>[metrics[k][0],metric(r,k),metrics[k][3]])));
    if(r.kind==='fund'){content.append(section('Reported holdings'),note(`Reported weight: ${percent((r.holdings||[]).reduce((s,h)=>s+h.weight,0))}. Unknown weight is not redistributed. Reporting date: ${r.holdings_as_of||'not supplied by source'}.`),table(['Holding','Name','Weight'],(r.holdings||[]).map(h=>[bySymbol.has(h.symbol)?instrumentLink(bySymbol.get(h.symbol)):h.symbol,h.name,percent(h.weight)])),section('Distributions'),table(['Ex-date','Amount','Currency'],(r.distributions||[]).slice(-20).reverse().map(d=>[d.date,num(d.amount),d.currency])));}
    const facts=r.financials||[];if(facts.length){content.append(section('Reported financial history'),table(['Metric','Period end','Value','Unit','Source'],facts.slice().sort((a,b)=>b.end.localeCompare(a.end)).map(f=>[f.metric,f.end,num(f.value),f.unit||r.currency,f.source])));}
    content.append(section('Original filings'),table(['Form','Date','Source'],(r.filings||[]).map(f=>[f.form,f.date,external('Read filing ↗',f.url)])),note('SEC records require SEC_USER_AGENT in the private environment; Yahoo financials are shown independently.'),section('Related news','#/news'),newsCards((data.news||[]).filter(n=>(n.tickers||[]).includes(r.symbol)||`${n.title} ${n.excerpt}`.toLowerCase().includes(r.name.toLowerCase())).slice(0,6)),resourceNote(r.symbol));
  }
  function compare(funds){const limit=funds?4:5;header(funds?'Funds, side by side.':'Put companies in perspective.',`Compare up to ${limit} loaded ${funds?'funds':'companies'}. History uses common dates and adjusted prices; facts retain original currencies.`);let selected=(new URLSearchParams(location.hash.split('?')[1]||'').get('symbols')||'').split(',').filter(s=>bySymbol.has(s));selected=[...new Set(selected)].filter(s=>funds?bySymbol.get(s).kind==='fund':bySymbol.get(s).kind==='stock').slice(0,limit);const input=el('input',{list:'symbol-options',placeholder:funds?'Add a fund ticker':'Add a stock ticker','aria-label':'Comparison ticker'}),message=el('p',{class:'error','aria-live':'polite'}),chips=el('div',{class:'comparison-chips'}),body=el('div',{class:'compare-grid'});function route(){location.hash=`#/${funds?'fund-compare':'compare'}?symbols=${selected.map(encodeURIComponent).join(',')}`;draw();}
    function add(){const symbol=input.value.toUpperCase().trim(),r=bySymbol.get(symbol);if(!r||(funds?r.kind!=='fund':r.kind!=='stock')){message.textContent='Choose a loaded '+(funds?'fund':'stock')+' ticker.';return;}if(selected.length>=limit&&!selected.includes(symbol)){message.textContent=`Maximum ${limit} instruments.`;return;}if(!selected.includes(symbol))selected.push(symbol);input.value='';message.textContent='';route();}
    function draw(){chips.replaceChildren(...selected.map(s=>button(s+' ×',()=>{selected=selected.filter(x=>x!==s);route();})));const rows=selected.map(s=>bySymbol.get(s));body.replaceChildren();if(!rows.length){body.append(empty('Add tickers above, or start with a comparison below.'));return;}const keys=funds?['assets','expense','year','annualized','volatility','drawdown','dividend_yield']:['market_cap','pe','pb','revenue_growth','net_margin','roe','debt_equity','dividend_yield'];body.append(table(['Metric',...rows.map(r=>r.symbol)],[[ 'Currency',...rows.map(r=>r.currency)],...keys.map(k=>[metrics[k][0],...rows.map(r=>metric(r,k))])]));const aligned=M.compareHistory(rows,bySymbol.get('SPY'));body.append(section('Growth of 10,000 · common dates'),el('div',{class:'card'},chart(aligned.dates,aligned.series,'Growth of hypothetical 10,000 investment on common dates','money')),note('Each series starts with 10,000 in its own currency. Adjusted prices approximate distributions/splits; no currency conversion or fees are applied.'));
      if(funds){const overlap=[];rows.forEach((a,i)=>rows.slice(i+1).forEach(b=>overlap.push([a.symbol+' / '+b.symbol,percent(M.fundOverlap(a,b))])));body.append(section('Disclosed holdings overlap'),table(['Funds','Common disclosed weight'],overlap),note('Overlap is a lower bound when the source reports only top holdings.'));}
      else{for(const metricName of ['Total Revenue','Free Cash Flow']){const units=[...new Set(rows.flatMap(r=>(r.financials||[]).filter(f=>f.metric===metricName&&M.numeric(f.value)).map(f=>f.unit||r.financial_currency||'Unknown')))];for(const unit of units){const series=rows.map(r=>({symbol:r.symbol,history:(r.financials||[]).filter(f=>f.metric===metricName&&M.numeric(f.value)&&(f.unit||r.financial_currency||'Unknown')===unit).map(f=>({date:f.end,close:f.value}))})).filter(s=>s.history.length);const dates=[...new Set(series.flatMap(s=>s.history.map(f=>f.date)))].sort();body.append(section(metricName+' / '+unit+' / available fiscal periods'),chart(dates,series.map(s=>({symbol:s.symbol,values:dates.map(d=>s.history.find(f=>f.date===d)?.close??null)})),metricName+' financial history in '+unit),note('Fiscal period ends, reporting currency '+unit+'. Different currencies are charted separately.'));}}}
    }
    content.append(el('div',{class:'toolbar'},input,button('Add to comparison',add,'primary'),button('Clear',()=>{selected=[];route();})),message,chips,body);input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();add();}});if(!selected.length)content.append(el('div',{class:'toolbar'},(funds?[['VOO','IVV','SPY'],['QQQ','QQQM'],['SCHD','VYM','DGRO']]:[['AAPL','MSFT','NVDA'],['JPM','BAC','GS']]).map(values=>button(values.join(' vs '),()=>{selected=values.filter(s=>bySymbol.has(s));route();}))));draw();
  }
  function families(){header('The people behind the funds.','Families in the published universe, with available costs and ETF assets. Mutual-fund share classes are not added together.');const groups=new Map();records.filter(r=>r.kind==='fund').forEach(r=>{if(!groups.has(r.family||'Unknown'))groups.set(r.family||'Unknown',[]);groups.get(r.family||'Unknown').push(r);});content.append(table(['Family','Loaded funds','Known ETF assets','Median expense','Members'],[...groups].sort((a,b)=>b[1].length-a[1].length).map(([name,rows])=>{const expenses=rows.map(r=>r.metrics?.expense).filter(M.numeric).sort((a,b)=>a-b),mid=Math.floor(expenses.length/2),median=expenses.length?expenses.length%2?expenses[mid]:(expenses[mid-1]+expenses[mid])/2:null;const assets=new Map();for(const r of rows.filter(r=>r.category!=='Mutual Fund'&&r.quote_type==='ETF')){if(!assets.has(r.currency))assets.set(r.currency,0);if(M.numeric(r.metrics?.assets))assets.set(r.currency,assets.get(r.currency)+r.metrics.assets);}return [name,rows.length,[...assets].map(([c,v])=>money(v,c)).join(' / ')||'Not verified',percent(median),el('div',{class:'actions'},rows.map(instrumentLink))];})),note('Coverage is the loaded fund basket, not every product in each family. Portfolio-level assets, fund flows and peer ranks require additional verified data.'),resourceNote('fund:'));}
  function lists(){header('Simple tests. Clear criteria.','Research lists apply visible predicates to available financial data. These are filters, not picks.');const list=M.presetLists(records),definitions={growers:['Profitable growers','Revenue growth ≥15%, net margin ≥10%, revenue ≥500M in reporting currency.'],cash:['Cash machines','Free cash flow margin ≥25%, revenue ≥1B.'],fortress:['Strong balance sheets','Cash exceeds debt, current ratio ≥2, revenue ≥500M.'],dividends:['Dividend payers','Positive provider dividend yield; sorted highest first.'],capital:['High returns on equity','ROE ≥25%, revenue ≥1B. ROE is not return on invested capital.'],largest:['Largest by sector','Grouped by sector and currency; market cap descending within each group.']};content.append(el('div',{class:'grid two'},Object.entries(definitions).map(([key,[title,definition]])=>el('div',{class:'card'},el('div',{class:'eyebrow'},list[key].length+' companies'),el('h2',{},title),el('p',{},definition),list[key].slice(0,5).map(r=>miniInstrument(r)),el('details',{},el('summary',{},'View all matching companies'),stockTable(list[key]))))),note('Ten-year compounders, consecutive dividend raisers, net insider purchases and quarterly institutional changes need sufficient comparable records; unavailable histories do not qualify.'));
  }
  function newsCards(rows){return rows.length?buildNewsCards(rows):empty('No available articles in this snapshot.');}
  function buildNewsCards(rows){return el('div',{class:'grid'},rows.map(n=>el('a',{class:'card news-card',href:`#/article/${encodeURIComponent(n.id)}`},el('div',{class:'news-art'}),el('div',{class:'news-meta'},(n.category||'News')+' / '+(n.published?stamp(n.published):'Date unavailable')),el('h3',{},n.title),el('p',{},(n.excerpt||'Read the source for the full report.').slice(0,220)),el('div',{class:'card-bottom'},el('span',{},n.publisher),el('span',{},'Read story ↗')))));}
  function apiQuotes(cryptoOnly=false){
    const rows=(data.api_data?.quotes||[]).filter(r=>cryptoOnly?r.source==='Kraken spot':r.source==='Alpaca IEX');
    return el('div',{},section(cryptoOnly?'Kraken spot observations':'IEX quote observations'),table(['Instrument','Mid / last','Bid','Ask','Currency','Provider time','Source status'],rows.map(r=>{const resource=(data.resources||[]).find(s=>s.id===(cryptoOnly?'Kraken:quotes':'Alpaca:quotes'));return [r.symbol,num(r.price,4),num(r.bid,4),num(r.ask,4),r.currency,r.observed_at?stamp(r.observed_at):'Not supplied by endpoint',r.source+' · '+(resource?.status||'unverified')+' · fetched '+stamp(resource?.fetched_at)];})),note(cryptoOnly?'Kraken REST ticker does not provide a quote timestamp. These are research observations, separate from Binance strategy candles.':'IEX is one venue. These cached observations are not consolidated quotes or trade-entry evidence.'),link('API setup and coverage →','#/coverage'));
  }
  function apiConnections(){return el('div',{},section('API connections'),note('Credentials stay in the local .env or GitHub Actions secrets. Missing setup is listed below; available means collected successfully, not guaranteed real-time.'),table(['Provider','Status','Purpose','Setup needed'],(data.api_data?.connections||[]).map(r=>[external(r.id+' ↗',r.url),r.status.replaceAll('_',' '),r.purpose,r.missing.length?r.missing.join(', '):'No required credentials missing'])),note('European filings use verified ticker-to-LEI mappings. Unmapped companies retain their existing research source. API refresh attempt: '+stamp(data.api_refreshed_at||data.generated_at)));}
  function coverage(){header('Know what’s behind the numbers.','Source status, actual coverage and freshness for this snapshot.','Data');content.append(apiConnections(),el('div',{class:'grid four'},el('div',{class:'card'},el('div',{class:'stat-label'},'Published instruments'),el('div',{class:'stat-value'},records.length)),el('div',{class:'card'},el('div',{class:'stat-label'},'Companies'),el('div',{class:'stat-value'},records.filter(r=>r.kind==='stock').length)),el('div',{class:'card'},el('div',{class:'stat-label'},'Funds'),el('div',{class:'stat-value'},records.filter(r=>r.kind==='fund').length)),el('div',{class:'card'},el('div',{class:'stat-label'},'Available news'),el('div',{class:'stat-value'},(data.news||[]).length))),section('Resource status'),table(['Resource','Status','Last successful fetch','Details'],(data.resources||[]).map(r=>[r.id,el('span',{class:r.status==='ok'?'up':'down'},r.status),stamp(r.fetched_at),r.error||'Available'])),resourceNote(),note('Saved screens and manually entered portfolios remain in your browser. News excerpts belong to their publishers; full articles stay at the source.'));
  }
  function portfolio(){header('See what you really own.','Look through your funds, find overlaps, and keep undisclosed exposure visible. Your entries stay in this browser.');let positions=[];try{positions=M.validatePortfolio(storage.get('portfolio',[]));}catch{}
    const symbol=el('input',{list:'symbol-options',placeholder:'e.g. SPY','aria-label':'Holding ticker'}),quantity=el('input',{type:'number',step:'any',min:'0',placeholder:'10','aria-label':'Holding quantity'}),purchase=el('input',{type:'number',step:'any',min:'0',placeholder:'Optional','aria-label':'Purchase price'}),date=el('input',{type:'date','aria-label':'Purchase date'}),message=el('p',{class:'error','aria-live':'polite'}),body=el('div',{});
    const form=el('form',{class:'card portfolio-form'},el('label',{},'Ticker',symbol),el('label',{},'Quantity',quantity),el('label',{},'Purchase price',purchase),el('label',{},'Purchase date',date),el('button',{type:'submit',class:'primary'},'Add holding'));
    function persist(){if(!storage.set('portfolio',positions))message.textContent='Browser storage is unavailable. Editing still works; export JSON to keep your entries.';}
    form.addEventListener('submit',event=>{event.preventDefault();try{const ticker=symbol.value.toUpperCase().trim(),record=bySymbol.get(ticker);if(!record||record.kind==='proxy')throw new Error('Choose a loaded stock or fund ticker.');const entry=M.validatePortfolio([{symbol:ticker,quantity:Number(quantity.value),purchase_price:purchase.value===''?null:Number(purchase.value),purchase_date:date.value||null}])[0];positions.push(entry);message.textContent='';persist();symbol.value='';quantity.value='';purchase.value='';date.value='';draw();}catch(error){message.textContent=error.message;}});
    const file=el('input',{type:'file',accept:'.json,application/json','aria-label':'Import portfolio JSON'});file.addEventListener('change',async()=>{try{const selected=file.files[0];if(!selected)return;if(selected.size>1e6)throw new Error('Portfolio file exceeds 1 MB.');const imported=M.validatePortfolio(JSON.parse(await selected.text()));positions=imported;message.textContent='';persist();draw();}catch(error){message.textContent='Import rejected: '+error.message;}finally{file.value='';}});
    function draw(){body.replaceChildren();const result=M.portfolioExposure(positions,records);
      const cards=Object.entries(result.currencies).map(([currency,b])=>el('div',{class:'card'},
        el('div',{class:'stat-label'},currency+' / positions with valid prices'),el('div',{class:'stat-value'},money(b.value,currency)),
        note(b.costed_value?'Costed positions: '+money(b.costed_value-b.cost,currency)+' unrealized P&L':'Cost basis not entered'),
        note('Undisclosed fund exposure: '+money(b.unknown,currency)),
        el('div',{class:'progress-track'},el('span',{style:`width:${b.value?(1-b.unknown/b.value)*100:0}%`}))));
      body.append(section('Portfolio value by currency'),el('div',{class:'grid'},cards));
      body.append(section('Your holdings'),table(['Holding','Quantity','Current value','Cost basis','Purchase date','Benchmark comparison',''],positions.map((p,i)=>{const r=bySymbol.get(p.symbol);let benchmark='Purchase date / history required';if(p.purchase_date&&r&&bySymbol.has('SPY')){const aligned=M.compareHistory([r],bySymbol.get('SPY')),index=aligned.dates.findIndex(d=>d>=p.purchase_date);if(index>=0&&index<aligned.dates.length-1){const a=aligned.series[0].values,b=aligned.series.find(s=>s.symbol==='SPY')?.values;if(b)benchmark=percent(a.at(-1)/a[index]-1)+' vs SPY '+percent(b.at(-1)/b[index]-1);}}return [r?instrumentLink(r):p.symbol,num(p.quantity,6),r&&M.numeric(r.price)?money(r.price*p.quantity,r.currency):'Price unavailable',p.purchase_price==null?'—':money(p.purchase_price*p.quantity,r?.currency||''),p.purchase_date||'—',benchmark,button('Remove',()=>{positions.splice(i,1);persist();draw();})];})));
      if(result.missing.length)body.append(note('Not valued: '+result.missing.join(', ')+'. Missing prices and currencies are not zero.'));
      body.append(section('Underlying exposure'),table(['Security','Position currency','Known value','Sector','Country','Held through'],result.underlying.map(r=>[r.symbol,r.currency,money(r.value,r.currency),r.sector,r.country,[...new Set(r.positions)].join(', ')])),note('Reported fund holdings are not rescaled. Unknown exposure is shown above, and funds with invalid total weights are treated as undisclosed. Holdings dates may be unavailable.'));
      for(const key of ['sector','country']){const grouped=new Map();result.underlying.forEach(r=>{const id=r.currency+' / '+r[key];grouped.set(id,(grouped.get(id)||0)+r.value);});body.append(section(key==='sector'?'Known sector mix':'Known country mix'),table([key==='sector'?'Sector / currency':'Country / currency','Known exposure'],[...grouped].sort((a,b)=>b[1]-a[1]).map(([name,value])=>[name,num(value)])));}
    }
    content.append(form,el('div',{class:'toolbar'},button('Export JSON ↓',()=>download('market-watch-portfolio.json',JSON.stringify(positions,null,2))),el('label',{},'Import JSON',file)),message,body);draw();
  }
  function markets(europe){const region=europe?'EU':'US';header(europe?'Across European markets.':'Today’s market, in focus.','Index proxies, sector moves and companies in the published universe. Freshness and coverage stay visible.','Markets');let period='day',mode='gainers';const body=el('div',{}),tabs=el('div',{class:'tabs'},['day','week','month','ytd','year'].map(key=>button(metrics[key][0],event=>{period=key;draw();})));content.append(el('div',{class:'toolbar'},tabs,link('Earnings →','#/earnings'),link('Dividends →','#/dividends'),link('IPOs →','#/ipos'),link('Economy →','#/economy')),body);if(!europe)content.append(apiQuotes());
    function draw(){[...tabs.children].forEach((b,i)=>b.classList.toggle('selected',['day','week','month','ytd','year'][i]===period));body.replaceChildren();const result=M.marketSummary(records,region,period),indices=europe?['^STOXX','^STOXX50E','^FTSE','^GDAXI','^FCHI','^AEX','^IBEX','^SSMI']:['SPY','QQQ','DIA','IWM','TLT','USO','GLD'];body.append(section(europe?'The indices':'Market benchmarks'),el('div',{class:'grid four'},indices.map(symbol=>{const r=bySymbol.get(symbol);return el('a',{class:'card',href:`#/instrument/${encodeURIComponent(symbol)}`},el('div',{class:'stat-label'},symbol),el('div',{class:'stat-value '+tone(r?.metrics?.[period])},percent(r?.metrics?.[period])),el('small',{},r?.name||'Index/proxy unavailable'),note(r?num(r.price)+' · '+(r.as_of||'date unavailable'):'No usable price'));})),note('US benchmarks are ETFs, not the underlying index level. European indices/proxies retain their trading currency. '+(result.asOf?'Equity summaries use '+result.asOf+'.':'No common equity observation date.')));
      if(europe){const indicesWithHistory=indices.slice(0,5).map(s=>bySymbol.get(s)).filter(Boolean),aligned=M.compareHistory(indicesWithHistory);body.append(section('Index history · rebased to 100'),el('div',{class:'card'},chart(aligned.dates,aligned.series.map(s=>({...s,values:s.values.map(v=>v/100)})),'European index history rebased to 100')),section('Currencies'),table(['Pair','Rate','1 year','Date'],records.filter(r=>r.symbol.endsWith('=X')).map(r=>[r.symbol,num(r.price,4),percent(r.metrics?.year),r.as_of||'—'])));}
      body.append(section('Sector perspective'),el('div',{class:'grid'},result.sectors.map(s=>el('div',{class:'card'},el('div',{class:'stat-label'},s.name+' / '+s.currency),el('div',{class:'stat-value '+tone(s.return)},percent(s.return)),note(s.count+' weighted companies · '+money(s.cap,s.currency))))),note('Market-cap weighted among records with valid weights and the common observation date. Different currencies are never silently added.'));
      const b=result.breadth;body.append(section('Market breadth'),el('div',{class:'grid four'},[['Advancing',b.up],['Declining',b.down],['New 52-week highs',b.highs],['New 52-week lows',b.lows],['Above 50-day average',percent(b.above50)],['Above 200-day average',percent(b.above200)],['Priced companies',b.count],['Covered companies',b.covered]].map(([name,value])=>el('div',{class:'card'},el('div',{class:'stat-label'},name),el('div',{class:'stat-value'},value)))),note('52-week highs/lows require 252 observations; moving-average percentages exclude insufficient histories. Breadth covers this basket, not the whole exchange.'));
      const moverTabs=el('div',{class:'tabs'},[['gainers','Gainers'],['losers','Losers'],['active','Most active'],['volume','Unusual volume'],['highs','New highs'],['lows','New lows']].map(([key,label])=>button(label,()=>{mode=key;draw();},mode===key?'selected':'')));let movers=[...result.rows];if(mode==='gainers')movers.sort((a,b)=>b.metrics[period]-a.metrics[period]);if(mode==='losers')movers.sort((a,b)=>a.metrics[period]-b.metrics[period]);if(mode==='active')movers=movers.filter(r=>M.numeric(r.metrics?.dollar_volume)).sort((a,b)=>b.metrics.dollar_volume-a.metrics.dollar_volume);if(mode==='volume')movers=movers.filter(r=>M.numeric(r.metrics?.relative_volume)).sort((a,b)=>b.metrics.relative_volume-a.metrics.relative_volume);if(mode==='highs'||mode==='lows')movers=movers.filter(r=>r.metrics?.[mode==='highs'?'new_high':'new_low']===true);body.append(section('Movers'),moverTabs,el('div',{style:'height:14px'}),stockTable(movers,['sector','price',period,'ytd','market_cap','relative_volume']));
      for(const currency of [...new Set(result.rows.map(r=>r.currency))].sort()){const tiles=result.rows.filter(r=>r.currency===currency&&M.numeric(r.metrics?.market_cap)&&r.metrics.market_cap>0).sort((a,b)=>b.metrics.market_cap-a.metrics.market_cap).slice(0,60),max=Math.max(...tiles.map(r=>r.metrics.market_cap),1);body.append(section('Company heat map / '+currency),el('div',{class:'card heatmap'},tiles.map(r=>el('a',{href:`#/instrument/${encodeURIComponent(r.symbol)}`,class:'heat-tile '+(r.metrics[period]>=0?'positive':'negative'),style:`flex-grow:${1+Math.sqrt(r.metrics.market_cap/max)*5};flex-basis:${72+Math.sqrt(r.metrics.market_cap/max)*80}px`,title:r.name+' / '+currency},el('b',{},r.symbol),el('span',{},percent(r.metrics[period]))))),note('Tile size approximates market cap within this currency basket.'));}
      if(europe)body.append(section('Countries'),table(['Country','Currency','Weighted companies','Known market cap',metrics[period][0]],result.countries.map(r=>[r.name,r.currency,r.count,money(r.cap,r.currency),percent(r.return)])));body.append(resourceNote('Yahoo:'));
    }draw();
  }
  function calendars(type){header(type==='earnings'?'When companies report.':'Upcoming dividend dates.',type==='earnings'?'Provider-supplied report dates and estimates for the published stock universe.':'Ex-dividend dates from the provider, with recent distributions shown separately.','Markets');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());let windowKey=type==='earnings'?'week':'seven';const body=el('div',{}),sector=el('select',{},options([...new Set(records.map(r=>r.sector))].sort(),'All sectors')),query=el('input',{type:'search',placeholder:'Filter ticker','aria-label':'Calendar ticker filter'}),windows=type==='earnings'?[['week','This week'],['next','Next week'],['later','Later'],['past','Just reported']]:[['seven','Next 7 days'],['next','Next week'],['month','Next 30 days'],['past','Recent distributions']],tabs=el('div',{class:'tabs'},windows.map(([key,name])=>button(name,()=>{windowKey=key;draw();})));sector.addEventListener('change',draw);query.addEventListener('input',draw);content.append(el('div',{class:'toolbar'},tabs,el('label',{},'Sector',sector),query),body);
    function draw(){body.replaceChildren();[...tabs.children].forEach((b,i)=>b.classList.toggle('selected',windows[i][0]===windowKey));let rows=records.flatMap(r=>(r.calendar||[]).map(c=>({...c,symbol:r.symbol,sector:r.sector,currency:r.currency})));if(windowKey==='past'&&type==='dividends')rows=records.flatMap(r=>(r.distributions||[]).map(c=>({...c,type:'dividends',symbol:r.symbol,sector:r.sector,status:'historical distribution',currency:r.currency})));rows=M.calendarRows(rows,type,windowKey,today).filter(r=>(!sector.value||r.sector===sector.value)&&(!query.value||r.symbol.toLowerCase().includes(query.value.toLowerCase())));body.append(table(type==='earnings'?['Company','Sector','Report date','Time / status']:['Company','Ex-date','Amount','Currency','Payment date','Status'],rows.map(r=>type==='earnings'?[bySymbol.has(r.symbol)?instrumentLink(bySymbol.get(r.symbol)):r.symbol,r.sector,r.date,(r.time?(r.time+' '+(r.timezone||'zone unavailable')):'Time unavailable')+' · '+r.status]:[bySymbol.has(r.symbol)?instrumentLink(bySymbol.get(r.symbol)):r.symbol,r.date,num(r.amount),r.currency,r.payment_date||'—',r.status])),note(type==='earnings'?'Upcoming provider dates are estimates unless explicitly confirmed. Historical report dates require source records.':'Historical distributions do not establish future dates. Amounts are omitted when the provider cannot link an amount to the upcoming event.'),resourceNote('calendar:'));
    }draw();
  }
  function ipos(){header('New listings. Clear facts.','Expected, priced, filed and withdrawn offerings from the available public calendar. Expected dates are estimates.','Markets');const filter=el('select',{},options(['expected','priced','filed','withdrawn'],'All offering stages')),body=el('div',{});content.append(el('div',{class:'toolbar'},el('label',{},'Stage',filter)),body);function draw(){const rows=(data.ipos||[]).filter(r=>!filter.value||r.status===filter.value);body.replaceChildren(table(['Company','Ticker','Stage','Date','Price / range','Shares','Amount','Exchange','Source'],rows.map(r=>[r.name,r.symbol||'—',r.status,r.date||'Date unavailable',r.price,r.shares,r.amount,r.exchange,external('Calendar ↗',r.url)])),note('Registration filings are not confirmed IPO dates. The source may be unavailable or incomplete.'),resourceNote('Nasdaq'));}filter.addEventListener('change',draw);draw();}
  function economy(){header('The economy behind the market.','Inflation, jobs, growth and rates, with original dates and units. Select an indicator to explore its history.','Markets');const history=el('div',{});content.append(el('div',{class:'grid'},(data.economy||[]).map(r=>{const card=el('div',{class:'card'},el('div',{class:'stat-label'},r.name),el('div',{class:'stat-value'},num(r.value)),el('small',{},r.unit),note('Latest '+(r.date||'unavailable')+' · Previous '+num(r.previous)),button('Explore history ↗',()=>{const rows=(r.history||[]).slice(-1200);history.replaceChildren(section(r.name+' / '+r.unit),el('div',{class:'card'},chart(rows.map(p=>p.date),[{symbol:r.name,values:rows.map(p=>p.value)}],r.name+' historical observations'),external('Original series ↗',r.url),note(r.source)));history.scrollIntoView({block:'start',behavior:'smooth'});}));return card;})),history,section('Official release calendar'));
    const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),windows=el('select',{},el('option',{value:'upcoming'},'Upcoming'),el('option',{value:'recent'},'Recent')),releases=el('div',{});function draw(){const rows=(data.releases||[]).filter(r=>windows.value==='upcoming'?r.date>=today:r.date<today).sort((a,b)=>windows.value==='upcoming'?a.date.localeCompare(b.date):b.date.localeCompare(a.date)).slice(0,70);releases.replaceChildren(table(['Date','Release','Time / zone','Source'],rows.map(r=>[r.date,r.name,(r.time?(r.time+' '+(r.timezone||'zone unavailable')):'Time unavailable')+' '+r.timezone,external(r.source+' ↗',r.url)])));}windows.addEventListener('change',draw);content.append(el('div',{class:'toolbar'},windows),releases,note('Official release dates; consensus forecasts are not supplied. Macro observations may be revised or delayed.'),resourceNote('FRED'));draw();}
  function news(longform){header(longform?'Read beyond the headline.':'What happened. Why it matters.',longform?'Long-form items from explicitly identified publisher feeds. Full articles remain at their sources.':'Search publisher headlines and supplied excerpts. Facts and attribution, without invented summaries.','News');const query=el('input',{type:'search',placeholder:'Search the news','aria-label':'Search the news'}),category=el('select',{},options([...new Set((data.news||[]).map(r=>r.category))].sort(),'All categories')),ticker=el('select',{},options([...new Set((data.news||[]).flatMap(r=>r.tickers||[]))].sort(),'All tickers')),body=el('div',{}),count=el('p',{class:'source-note'});content.append(el('div',{class:'toolbar'},query,category,ticker,button('Reset',()=>{query.value='';category.value='';ticker.value='';draw();})),count,body,resourceNote('Feed'));function draw(){const rows=M.newsRows(data.news||[],{query:query.value,category:category.value,ticker:ticker.value,longform});count.textContent=rows.length+' articles · supplied publisher excerpts';body.replaceChildren(newsCards(rows));}[query,category,ticker].forEach(x=>x.addEventListener('input',draw));draw();}
  function article(id){const row=(data.news||[]).find(n=>n.id===id);if(!row){header('Article not in this snapshot.','News items can change between refreshes.');content.append(link('Return to latest news','#/news'));return;}content.append(el('article',{class:'article'},link('← Latest news','#/news'),el('div',{class:'eyebrow',style:'margin-top:30px'},row.category+' / '+row.publisher),el('h1',{},row.title),note(stamp(row.published)),el('div',{class:'card'},el('p',{class:'article-excerpt'},row.excerpt||'The source did not provide an excerpt.'),external('Read the original article ↗',row.url)),note('Publisher-supplied excerpt. The full article and any paywall remain at the source.'),el('div',{class:'actions'},(row.tickers||[]).filter(s=>bySymbol.has(s)).map(s=>instrumentLink(bySymbol.get(s))))));}
  function crypto(){header('Crypto market desk.','Exchange observations, market overview and completed strategy candles, each attributed to its source.','Markets');let rows=[];try{const source=JSON.parse(document.getElementById('strategy-data').textContent);rows=source.results.filter(r=>r.market==='crypto');}catch{}content.append(apiQuotes(true),section('CoinGecko market overview'),table(['Coin','Price USD','24h change','Market cap USD','Provider time'],(data.api_data?.crypto||[]).map(r=>[r.name,num(r.price,4),percent(r.change),money(r.market_cap,'USD'),stamp(r.observed_at)])),external('Data provided by CoinGecko ↗','https://www.coingecko.com/'),resourceNote('CoinGecko'),section('Binance strategy evidence'),table(['Pair','Latest completed close','Regime','Setup','Relative volume','Evidence'],rows.map(r=>[r.symbol,num(r.candles?.at(-1)?.close,8),r.regime,r.status,num(r.volume_ratio),link('Open breakout evidence ↗','#/breakout')])),note('Completed strategy candles; no executable quote or live streaming price is implied.'));}
  function entrydesk(){
    header('Entry evidence desk.','Patterns are research candidates. Missing quotes, confirmation, costs or validation veto readiness.','Strategy');
    const snapshot=JSON.parse(document.getElementById('entry-data')?.textContent||'{"candidates":[]}'), rows=snapshot.candidates||[];
    const asset=el('select',{'aria-label':'Filter asset class'},options([...new Set(rows.map(r=>r.asset_class).filter(Boolean))],'All assets'));
    const state=el('select',{'aria-label':'Filter candidate state'},options([...new Set(rows.map(r=>r.state).filter(Boolean))],'All states'));
    const results=el('div');content.append(el('div',{class:'filters'},asset,state),note(`Snapshot ${stamp(snapshot.generated_at)} · ${snapshot.status||'Unavailable'}. Score is not a probability. Paper readiness requires holdout and forward paper evidence.`),results);
    function update(){results.replaceChildren(table(['Instrument / source','State / side','Entry / stop / target','Net R:R / score','Evidence'],rows.filter(r=>(!asset.value||r.asset_class===asset.value)&&(!state.value||r.state===state.value)).map(r=>[el('div',{},r.symbol,el('small',{},`${r.asset_class||'Unknown'} · ${r.source||'Unknown source'} · ${stamp(r.as_of)}`)),`${r.state||'Unavailable'} / ${r.side||'—'}`,el('div',{},`${num(r.entry)} / ${num(r.stop)} / ${num(r.target)}`,r.reference_levels?el('small',{},`Reference only: ${num(r.reference_levels.entry)} / ${num(r.reference_levels.stop)} / ${num(r.reference_levels.target)} · non-executable`):null),`${num(r.net_rr)} / ${num(r.score)}`,el('details',{},el('summary',{},'Factors, vetoes and validation'),el('p',{},(r.reasons||[]).join(' · ')||'No readiness evidence supplied'),el('pre',{},JSON.stringify({factors:r.factors||{},reference_levels:r.reference_levels||null,validation:r.validation||{}},null,2)))])),el('details',{},el('summary',{},'Validation summary and provider errors'),el('pre',{},JSON.stringify({validation:snapshot.validation||{},errors:snapshot.errors||[]},null,2))));}
    asset.addEventListener('change',update);state.addEventListener('change',update);update();
  }
  function render(){content.replaceChildren();const [path]=location.hash.startsWith('#/')?location.hash.slice(2).split('?'):['home'],[rawRoute,rawArgument]=path.split('/'),route=rawRoute||'home';let argument='';try{argument=decodeURIComponent(rawArgument||'');}catch{}document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));document.getElementById('crumb').textContent=labels[route]||'Instrument';document.getElementById('breakout-panel').hidden=route!=='breakout';const technical=document.getElementById('technical-panel');if(technical)technical.hidden=route!=='technical';if(route==='entrydesk')entrydesk();else if(route==='technical')header('Desk Tape.','Original technical analysis, backtests and market snapshot.','Markets');else if(route==='home')home();else if(route==='screener'||route==='funds')screener(route==='funds'?'fund':'stock');else if(route==='instrument')detail(argument);else if(route==='compare'||route==='fund-compare')compare(route==='fund-compare');else if(route==='families')families();else if(route==='lists')lists();else if(route==='portfolio')portfolio();else if(route==='markets'||route==='europe')markets(route==='europe');else if(route==='earnings'||route==='dividends')calendars(route);else if(route==='ipos')ipos();else if(route==='economy')economy();else if(route==='news'||route==='reads')news(route==='reads');else if(route==='article')article(argument);else if(route==='crypto')crypto();else if(route==='coverage')coverage();else if(route==='breakout'){header('Your breakout research desk.','Original strategy, evidence, track record and simulated paper journal.','Strategy');content.style.minHeight='0';}else {header('Page unavailable','Choose a destination from the navigation.');}if(route!=='breakout')content.style.minHeight='';document.title=(labels[route]||'Instrument')+' · Market Watch';}
  document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();content.focus();});
  document.getElementById('symbol-options').replaceChildren(...records.map(r=>el('option',{value:r.symbol},r.name)));
  document.getElementById('global-search').addEventListener('submit',event=>{event.preventDefault();const value=document.getElementById('global-symbol').value.trim(),found=records.find(r=>r.symbol.toLowerCase()===value.toLowerCase()||r.name.toLowerCase()===value.toLowerCase());location.hash='#/instrument/'+encodeURIComponent(found?.symbol||value.toUpperCase());});
  const theme=storage.get('theme','dark');document.documentElement.dataset.theme=theme==='light'?'light':'dark';document.getElementById('theme').addEventListener('click',()=>{const value=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=value;storage.set('theme',value);});
  window.addEventListener('hashchange',render);document.getElementById('breakout-frame').addEventListener('load',event=>{try{event.target.style.height=event.target.contentDocument.documentElement.scrollHeight+'px';}catch{}});render();
})();
