const assert=require('node:assert/strict');
const FX=require('../../src/screener/usd_display.js');
const now=Date.parse('2026-10-04T06:00:00Z')/1000;
const fx=(symbol,price,as_of='2026-10-02',history=[])=>({symbol,price,as_of,history,source:'Test source'});
const snapshot={instruments:[fx('EURUSD=X',1.2),fx('GBPUSD=X',1.4),fx('EURCHF=X',.96),fx('EURDKK=X',7.5,'2026-10-04',[{date:'2026-10-02',close:7.2}])],api_data:{crypto:[{id:'tether',symbol:'USDT',currency:'USD',price:.99,observed_at:'2026-10-04T05:00:00Z',source:'CoinGecko'}]}};
const original=JSON.stringify(snapshot), rates=FX.create(snapshot,now);
assert.equal(rates.convert(100,'USD'),100);
assert.equal(rates.convert(100,'EUR'),120);
assert.equal(rates.convert(100,'GBP'),140);
assert.equal(rates.convert(100,'GBp'),1.4);
assert.equal(rates.convert(100,'GBX'),1.4);
assert.equal(rates.convert(100,'CHF'),125);
assert.ok(Math.abs(rates.convert(72,'DKK')-12)<1e-10);
assert.equal(rates.rates.DKK.date,'2026-10-02');
assert.equal(rates.convert(100,'USDT'),99);
assert.equal(rates.convert(0,'EUR'),0);
assert.equal(rates.convert(-100,'EUR'),-120);
for(const v of [null,undefined,NaN,Infinity,'100',true]) assert.equal(rates.convert(v,'USD'),null);
assert.equal(rates.convert(100,'UNKNOWN'),null);
assert.equal(FX.create({instruments:[fx('EURUSD=X',1.2,'2026-09-01')]},now).convert(100,'EUR'),null);
assert.equal(FX.create({instruments:[fx('EURUSD=X',1.2,'2026-10-05')]},now).convert(100,'EUR'),null);
assert.equal(FX.create({instruments:[fx('EURUSD=X',0)]},now).convert(100,'EUR'),null);
assert.equal(FX.create({instruments:[fx('EURUSD=X',1.2),fx('EURCHF=X',.96,'2026-10-01')]},now).convert(100,'CHF'),null);
assert.equal(FX.create({instruments:snapshot.instruments,resources:[{id:'Yahoo:history:EURUSD=X',status:'stale'}]},now).convert(100,'EUR'),null);
assert.equal(FX.create({},now).convert(100,'USDT'),null);
assert.equal(FX.create({api_data:{crypto:[{id:'tether',currency:'USD',price:.99,observed_at:'2026-09-30T00:00:00Z'}]}},now).convert(100,'USDT'),null);
assert.equal(FX.format(.0000001234), '$0.0000001234');
assert.equal(FX.format(null), 'USD unavailable');
assert.equal(FX.format(1234.5), '$1,234.50');
assert.equal(FX.format(1234567890,true), '$1.23B');
assert.equal(JSON.stringify(snapshot),original);
console.log('USD display checks passed: units, cross dates, stale/missing FX, USDT, precision and immutability');

assert.equal(FX.monetaryUnit('EUR/xbrli:shares').currency,'EUR');
assert.equal(FX.monetaryUnit('USD/shares').perShare,true);
assert.equal(FX.monetaryUnit('shares'),null);
assert.equal(FX.monetaryUnit('ratio'),null);

assert.equal(FX.format(1.234e-25),'$1.234e-25');
assert.equal(FX.create({...snapshot,resources:[{id:'CoinGecko:markets',status:'stale'}]},now).convert(100,'USDT'),null);
